### ISSUE TITLE
JudoPay Android - Stop showing "No Connection" when the problem is due to using the wrong environment

### ISSUE THREAD

**Issue by SaikCaskey** [Judopay/Android-Sample-App#1]
The JudoPay Android SDK has been removed, so I can't put an issue there, hope you see this.

When you fail to add a test card because your judo environment is set to UAT (and presumably Live), the message that is displayed says something like "No Connection" - and I can see it's an intentional callback, but this is extremely unhelpful for debugging.

Could this message be something slightly different? Even if the text needs to stay the same for the user's benefit, a different code or some logcat that says "No... you can't use this environment for that card"

I flicked to our different build variant and released, then people reported that they had a fine network connection (and had downloaded the app meta data) but could not add a card because they didn't have a network connection, making our app look very stupid and frustrating to use!!

Thanks guys :)

**Comment by jamesgoodwin** [comment]
Hi @SaikCaskey,

Thanks for reporting the issue and sorry to hear you found a bug. The UAT environment was included in the SDK for internal testing but has since been removed in the latest version of the SDK (5.6.5).

Are you able to recreate the issue another way in v5.6.5?

Thanks,
James

**Comment by SaikCaskey** [comment]
I haven't seen this yet James, I will reopen this if I come across it, but if you've removed UAT it should be fine, cheers!
